# Common parameters
namespaceId:
  type: text/plain
  value: |
    Namespace identifier.
tenantId:
  type: text/plain
  value: |
    Tenant identifier.
query:
  type: text/plain
  value: |
    Query identifier.
count:
  type: text/plain
  value: |
    Parameter representing the maximum number of objects to retrieve. If unspecified, a default value of 100 is used.
skip:
  type: text/plain
  value: |
    Parameter representing the zero-based offset of the first object to retrieve.  If unspecified, a default value of 0 is used.
key:
  type: text/plain
  value: |
    Key specifying the metadata value of interest.
cancellation-token:
  type: text/plain
  value: |
    Cancellation token.
scheme:
  type: text/plain
  value: |
    Scheme name (for example, AAD or Google).
# Community parameters
tenantId-community:
  type: text/plain
  value: |
    Owning tenant identifier.
communityId:
  type: text/plain
  value: |
    Community identifier.
query-community:
  type: text/plain
  value: |
    (Not supported) Query identifier.
# Tenant identifier parameters for AAD when there are different types of tenants to have to consider and distinguish
tenantId-OCS:
  type: text/plain
  value: |
    OCS tenant identifier.
tenantId-aad:
  type: text/plain
  value: |
    Azure Active Directory tenant identifier.
groupId:
  type: text/plain
  value: |
    Group identifier.
clientId:
  type: text/plain
  value: |
    Client identifier.
streamId:
  type: text/plain
  value: |
    Stream identifier.
# Identity provider focused identifiers
identityProviderId:
  type: text/plain
  value: |
    Identity provider identifier.
identityProviderClaimId:
  type: text/plain
  value: |
    Identity provider claim identifier.
identityProviderTypeNameClaimId:
  type: text/plain
  value: |
    Identity provider claim type name identifier.
# Other types of identifiers
invitationId:
  type: text/plain
  value: |
    Invitation identifier.
userId:
  type: text/plain
  value: |
    User identifier.
datasourceId:
  type: text/plain
  value: |
    Data source identifier.
dataViewId:
  type: text/plain
  value: |
    Data view identifier.
# OMF parameters
subscriptionId:
  type: text/plain
  value: |
    Subscription identifier.
topicId:
  type: text/plain
  value: |
    Topic identifier.
secretId:
  type: text/plain
  value: |
    Secret identifier.
# Used for getting a list of identifiers in a GET method
id:
  type: text/plain
  value: |
    Unordered list of identifiers for all clients to get. Empty or whitespace identifiers will be ignored.
tag:
  type: text/plain
  value: |
    Only return clients that have these tags.
# Query for wildcard search 
query-searchstring:
  type: text/plain
  value: |
    (Not supported) Search string identifier.
