array:
  Type: array
  Format: |
    
  SDSTypeCode: |
    IENumerable
boolean:
  Type: boolean
  Format: |
    
  SDSTypeCode: |
    boolean
integer:
  Type: integer
  Format: |
    int64
  SDSTypeCode: |
    Int64
integer:
  Type: integer
  Format: |
    int32
  SDSTypeCode: |
    Int32
integer:
  Type: integer
  Format: |
    int16
  SDSTypeCode: |
    Int16
integer:
  Type: integer
  Format: |
    uint64
  SDSTypeCode: |
    Uint64    
