namespaceId:
  type: text/plain
  value: |
    Namespace identifier
tenantId:
  type: text/plain
  value: |
    Tenant identifier
aadTenantId:
  type: text/plain
  value: |
    Azure Active Directory tenant identifier
tenantId-OCS:
  type: text/plain
  value: |
    OCS tenant identifier
aadCount:
  type: text/plain
  value: |
    Maximum number of Azure Active Directory tenants to return
aadSkip:
  type: text/plain
  value: |
    Number of Azure Active Directory tenants to skip
aadQuery:
  type: text/plain
  value: |
    (Not supported) Query identifier
groupId:
  type: text/plain
  value: |
    Group identifier
clientId:
  type: text/plain
  value: |
    Client identifier
id:
  type: text/plain
  value: |
    Unordered list of identifiers for all clients to get. Empty or whitespace identifiers will be ignored.
tag:
  type: text/plain
  value: |
    Only return clients that have these tags
query:
  type: text/plain
  value: |
    Query identifier
count:
  type: text/plain
  value: |
    Parameter representing the maximum number of objects to retrieve. If unspecified, a default value of 100 is used.
skip:
  type: text/plain
  value: |
    Parameter representing the zero-based offset of the first object to retrieve.  If unspecified, a default value of 0 is used.
query-identity:
  type: text/plain
  value: |
    (Not supported) Query identifier
count-identity:
  type: text/plain
  value: |
    Maximum number of clients to return. Default value is 100.
skip-identity:
  type: text/plain
  value: |
    Number of clients to skip
streamId:
  type: text/plain
  value: |
    Stream identifier
key:
  type: text/plain
  value: |
    Key specifying the metadata value of interest
identityProviderId:
  type: text/plain
  value: |
    Identity provider identifier
identityProviderClaimId:
  type: text/plain
  value: |
    Identity provider claim identifier
identityProviderTypeNameClaimId:
  type: text/plain
  value: |
    Identity provider claim type name identifier
identityProviderCount:
  type: text/plain
  value: |
    Maximum number of identity providers to return
identityProviderSkip:
  type: text/plain
  value: |
    Number of identity providers to skip
clientcredentialclientId:
  type: text/plain
  value: |
    Client credential client identifier
clientcredentialclientCount:
  type: text/plain
  value: |
    Maximum number of roles to return
clientcredentialclientSkip:
  type: text/plain
  value: |
    Number of roles to skip
tenantId-community:
  type: text/plain
  value: |
    Owning tenant identifier
query-community:
  type: text/plain
  value: |
    (Not supported) Query identifier
communityId:
  type: text/plain
  value: |
    Community identifier
invitationId:
  type: text/plain
  value: |
    Invitation identifier
userId:
  type: text/plain
  value: |
    User identifier
datasourceId:
  type: text/plain
  value: |
    Data source identifier
dataViewId:
  type: text/plain
  value: |
    Data view identifier
cancellation-token:
  type: text/plain
  value: |
    Cancellation token
subscriptionId:
  type: text/plain
  value: |
    Subscription identifier
topicId:
  type: text/plain
  value: |
    Topic identifier