namespaceId:
  type: text/plain
  value: |
    Namespace identifier
tenantId:
  type: text/plain
  value: |
    Tenant identifier
aadTenantId:
  type: text/plain
  value: |
    Active Directory Tenant identifier
aadCount:
  type: text/plain
  value: |
    Maximum number of Azure Active Directory tenants to return
aadSkip:
  type: text/plain
  value: |
   Number of Azure Active Directory tenants to skip
clientId:
  type: text/plain
  value: |
    Client identifier
id:
  type: text/plain
  value: |
    Unordered list of Ids for all clients to get. Empty or whitespace Ids will be ignored.
tag:
  type: text/plain
  value: |
    Only return clients that have these tags
query:
  type: text/plain
  value: |
    (Not supported) Query identifier
count:
  type: text/plain
  value: |
    Maximum number of clients to return. Default value is 100.
skip:
  type: text/plain
  value: |
   Number of clients to skip
streamId:
  type: text/plain
  value: |
    Stream identifier
key:
  type: text/plain
  value: |
    Key specifying the metadata value of interest
identityProviderId:
  type: text/plain
  value: |
    Identity provider identifier
identityProviderClaimId:
  type: text/plain
  value: |
    Identity provider claim unique identifier
identityProviderTypeClaimId:
  type: text/plain
  value: |
    Identity provider claim type name unique identifier
identityProviderCount:
  type: text/plain
  value: |
    Maximum number of identity providers to return
identityProviderSkip:
  type: text/plain
  value: |
    Number of identity providers to skip
clientcredentialclientId:
  type: text/plain
  value: |
    Client credential client unique identifier
clientcredentialclientCount:
  type: text/plain
  value: |
    Max number of roles to return
clientcredentialclientSkip:
  type: text/plain
  value: |
    Number of roles to skip
tenantId-community:
  type: text/plain
  value: |
    Owning tenant identifier
query-community:
  type: text/plain
  value: |
    (Not supported) Query identifier
communityId:
  type: text/plain
  value: |
    Community identifier
invitationId:
  type: text/plain
  value: |
    Invitation identifier
userId:
  type: text/plain
  value: |
    User identifier
datasourceId:
  type: text/plain
  value: |
    Data source identifier
dataViewId:
  type: text/plain
  value: |
    Data view identifier
cancellation-token:
  type: text/plain
  value: |
    Cancellation token
subscriptionId:
  type: text/plain
  value: |
    Subscription identifier
topicId:
  type: text/plain
  value: |
    Topic identifier