<!DOCTYPE html>
<!--[if IE]><![endif]-->
<html>
  
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Topics  </title>
    <meta name="viewport" content="width=device-width">
    <meta name="title" content="Topics  ">
    <meta name="generator" content="docfx 2.39.2.0">
    
    <link rel="shortcut icon" href="../../favicon.ico">
    <link rel="stylesheet" href="../../styles/docfx.vendor.css">
    <link rel="stylesheet" href="../../styles/docfx.css">
    <link rel="stylesheet" href="../../styles/main.css">
    <meta property="docfx:navrel" content="../../toc.html">
    <meta property="docfx:tocrel" content="../toc.html">
    
    
    
  </head>
  <body data-spy="scroll" data-target="#affix" data-offset="120">
    <div id="wrapper">
      <header>
        
        <nav id="autocollapse" class="navbar navbar-inverse ng-scope" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              
              <a class="navbar-brand" href="../../index.html">
                <img id="logo" src="../../images/atlas_icon.png" alt="">
              </a>    </div>
            <div class="collapse navbar-collapse" id="navbar">
              <form class="navbar-form navbar-right" role="search" id="search">
                <div class="form-group">
                  <input type="text" class="form-control" id="search-query" placeholder="Search" autocomplete="off">
                </div>
              </form>
            </div>
          </div>
        </nav>
        
        <div class="subnav navbar navbar-default">
          <div class="container hide-when-search" id="breadcrumb">
            <ul class="breadcrumb">
              <li></li>
            </ul>
          </div>
        </div>
      </header>
      <div role="main" class="container body-content hide-when-search">
        
        <div class="sidenav hide-when-search">
          <a class="btn toc-toggle collapse" data-toggle="collapse" href="#sidetoggle" aria-expanded="false" aria-controls="sidetoggle">Show / Hide Table of Contents</a>
          <div class="sidetoggle collapse" id="sidetoggle">
            <div id="sidetoc"></div>
          </div>
        </div>
        <div class="article row grid-right">
          <div class="col-md-10">
            <article class="content wrap" id="_content" data-uid="omfIngressTopics">
<h1 id="topics-">Topics </h1>

<h2 id="topic-information-">Topic information </h2>
<p>A Topic is used to aggregate data received from publishers and make it available for consumption 
via a Subscription. A topic must contain at least one publisher. Publishers may be added to or 
removed from an existing topic. A given publisher may also belong to multiple topics. </p>
<p>When a topic is created, data sent from its assigned publishers is routed to a special queue 
where it can be consumed by a subscription. This queue provides a buffer of up to one day for 
subscriptions which are temporarily unable to receive data. </p>
<p>The API calls in this section are used to create and manipulate topics. </p>
<h2 id="data-models-">Data Models </h2>
<p>Topic information is contained in an object called <code>Topic</code> and has the following format: </p>
<table>
<thead>
<tr>
<th>Property</th>
<th>Type</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr>
<td>TenantId</td>
<td>string</td>
<td>Identifies the owner of the Topic</td>
</tr>
<tr>
<td>Id</td>
<td>string</td>
<td>Unique Id generated by the API during creation</td>
</tr>
<tr>
<td>NamespaceId</td>
<td>string</td>
<td>Identifies the namespace for the Topic</td>
</tr>
<tr>
<td>Name</td>
<td>string</td>
<td>A friendly name for the Topic</td>
</tr>
<tr>
<td>Description</td>
<td>string</td>
<td>An optional description for the Topic.</td>
</tr>
<tr>
<td>CreationDate</td>
<td>string</td>
<td>The time that the Topic was created. The string is formatted using ISO 8601 format.</td>
</tr>
<tr>
<td>Publishers</td>
<td>string array</td>
<td>An array of Publisher Ids mapped to the Topic</td>
</tr>
</tbody>
</table>
<hr>
<h2 id="get-apitenantstenantidnamespacesnamespaceidtopicscount"><code>GET api/tenants/{tenantId}/namespaces/{namespaceId}/topics/count</code></h2>
<p>Get the number of topics for a tenant. </p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace.</p>
<p><strong>Returns</strong></p>
<p>An integer. </p>
<hr>
<h2 id="get-apitenantstenantidnamespacesnamespaceidtopicstopicid"><code>GET api/tenants/{tenantId}/namespaces/{namespaceId}/topics/{topicId}</code></h2>
<p>Get a specific topic. </p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>topicId</code>
  Unique Id for the topic. 
<code>namespaceId</code>
  Unique Id for the namespace.</p>
<p><strong>Returns</strong></p>
<p>A Topic object. </p>
<hr>
<h2 id="get-apitenantstenantidnamespacesnamespaceidtopicsskipskipcountcount"><code>GET api/tenants/{tenantId}/namespaces/{namespaceId}/topics?skip={skip}&amp;count={count}</code></h2>
<p>Get all topics for a tenant. </p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace.
<code>int skip</code>
  An optional parameter representing the zero-based offset of the first topic to retrieve. If not specified, a default value of 0 is used. 
<code>int count</code>
  An optional parameter representing the maximum number of topics to retrieve. If not specified, a default value of 100 is used.</p>
<p><strong>Returns</strong></p>
<p>An array of Topic objects. </p>
<hr>
<h2 id="get-apitenantstenantidnamespacesnamespaceidtopicstopicidsubscriptionsskipskipcountcount"><code>GET api/tenants/{tenantId}/namespaces/{namespaceId}/topics/{topicId}/subscriptions?skip={skip}&amp;count={count}</code></h2>
<p>Get all subscriptions across all namespaces mapped to a topic.</p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace of the topic.
<code>topicId</code>
  Unique Id for the topic.
<code>int skip</code>
  An optional parameter representing the zero-based offset of the first subscription mapped to a topic to retrieve. If not specified, a default value of 0 is used. 
<code>int count</code>
  An optional parameter representing the maximum number of subscriptions mapped to a topic to retrieve. If not specified, a default value of 100 is used.</p>
<p><strong>Returns</strong></p>
<p>An array of Subscription objects. </p>
<hr>
<h2 id="get-apitenantstenantidnamespacesnamespaceidpublishertopicmappingstopictopicidskipskipcountcount"><code>GET api/tenants/{tenantId}/namespaces/{namespaceId}/publishertopicmappings/topic/{topicId}?skip={skip}&amp;count={count}</code></h2>
<p>Gets a list of publishers that are currently mapped to a topic </p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace of the topic.
<code>topicId</code>
  Unique Id for the topic. 
<code>int skip</code>
  An optional parameter representing the zero-based offset of the first publisher mapped to a topic to retrieve. If not specified, a default value of 0 is used. 
<code>int count</code>
  An optional parameter representing the maximum number of publishers mapped to a topic to retrieve. If not specified, a default value of 100 is used.</p>
<p><strong>Returns</strong></p>
<p>An array of strings, each the Id of a publisher that is mapped to the provided topic</p>
<hr>
<h2 id="get-apitenantstenantidnamespacesnamespaceidaccesscontroltopics"><code>GET api/tenants/{tenantId}/namespaces/{namespaceId}/accesscontrol/topics</code></h2>
<p>Gets the default Access Control List for new topics.</p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace. </p>
<p><strong>Returns</strong></p>
<p>An AccessControlList object.</p>
<hr>
<h2 id="get-apitenantstenantidnamespacesnamespaceidtopicstopicidaccesscontrol"><code>GET api/tenants/{tenantId}/namespaces/{namespaceId}/topics/{topicId}/accesscontrol</code></h2>
<p>Gets the Access Control List for a particular topic.</p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace. 
<code>topicId</code>
  Unique Id for the topic. </p>
<p><strong>Returns</strong></p>
<p>An AccessControlList object.</p>
<hr>
<h2 id="post-apitenantstenantidnamespacesnamespaceidtopic"><code>POST api/tenants/{tenantId}/namespaces/{namespaceId}/topic</code></h2>
<p>Creates or updates a topic. Only the topic name and description can be updated. </p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace. </p>
<p><strong>Body</strong></p>
<p>A MappedTopic object. </p>
<p><strong>Returns</strong></p>
<p>A MappedTopic object. </p>
<hr>
<h2 id="put-apitenantstenantidnamespacesnamespaceidaccesscontroltopics"><code>PUT api/tenants/{tenantId}/namespaces/{namespaceId}/accesscontrol/topics</code></h2>
<p>Update the default Access Control List for new topics</p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace. </p>
<p><strong>Body</strong></p>
<p>An AccessControlList object.</p>
<hr>
<h2 id="put-apitenantstenantidnamespacesnamespaceidtopicstopicidaccesscontrol"><code>PUT api/tenants/{tenantId}/namespaces/{namespaceId}/topics/{topicId}/accesscontrol</code></h2>
<p>Update the Access Control List for a particular topic</p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace. 
<code>topicId</code>
  Unique Id for the topic. </p>
<p><strong>Body</strong></p>
<p>An AccessControlList object.</p>
<hr>
<h2 id="delete-apitenantstenantidnamespacesnamespaceidtopicstopicid"><code>DELETE api/tenants/{tenantId}/namespaces/{namespaceId}/topics/{topicId}</code></h2>
<p>Delete a topic. </p>
<p><strong>Parameters</strong></p>
<p><code>tenantId</code>
  Unique Id for the tenant. 
<code>namespaceId</code>
  Unique Id for the namespace. 
<code>topicId</code>
  Unique Id for the topic. </p>
<hr>
</article>
          </div>
          
          <div class="hidden-sm col-md-2" role="complementary">
            <div class="sideaffix">
              <div class="contribution">
                <ul class="nav">
                  <li>
                    <a href="https://github.com/osisoft/OCS-Docs/blob/master/Documentation/DataIngress/OMF_Ingress_Topics.md/#L1" class="contribution-link">Improve this Doc</a>
                  </li>
                </ul>
              </div>
              <nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix" id="affix">
              <!-- <p><a class="back-to-top" href="#top">Back to top</a><p> -->
              </nav>
            </div>
          </div>
        </div>
      </div>
      
      <footer>
        <div class="grad-bottom"></div>
        <div class="footer">
            <span id='copyright-text'>© 2018 - OSIsoft, LLC.<span>
        </span></span></div>
      </footer>
    </div>
    
    <script type="text/javascript" src="../../styles/docfx.vendor.js"></script>
    <script type="text/javascript" src="../../styles/docfx.js"></script>
    <script type="text/javascript" src="../../styles/main.js"></script>
  </body>
</html>
